#!/bin/bash

#DEBHELPER#

LASTVERSION=7.0.5~
case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" le "$LASTVERSION"; then
        sed -i '/Kurjun/d;/AppDataPrefix/d;s/SSLPort.*/SSLPort = 443/' /etc/subutai/agent.conf
    fi
esac
