#!/bin/bash

#DEBHELPER#

LASTVERSION=7.0.6~
case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" le "$LASTVERSION"; then
        #sed -i '/Kurjun/d;/AppDataPrefix/d;s/SSLPort.*/SSLPort = 443/;s/cdn.subutai.io/bazaar.subutai.io/' /etc/subutai/agent.conf
        cp /usr/lib/subutai/etc/agent.conf /etc/subutai/
    fi
esac

if systemctl is-active --quiet ipfs.service; then
    export IPFS_PATH=/var/lib/ipfs/node
    ipfs bootstrap add /dnsaddr/eu1.s.optdyn.com/ipfs/QmUZFuJ31ctYGxYFDtKzDBXmpmiBQWZGyqQChL7RwQNitV
    ipfs bootstrap add /dnsaddr/us1.s.optdyn.com/ipfs/QmdL6K8gqGT2BRUEGtcnRGTCyGVV5H7QiYqPLzvgMcLpxo
fi
