#!/bin/bash

# this script restores forwarding rules for port 22 (SSH) of containers
# for various reasons these rules might disappear during normal operation of peer (no reboot!)
# NOTE after peer reboot these rules are restored by containers' "lxc.network.script.up" script so no need to make them persistent

function checkNRestore(){

    MISSING_IPS=()

    # iterate over IPs of running containers
    for containerIp in `subutai list i | grep -e 'RUNNING.*172.' | tr -s [:blank:] | cut -f3` ; do

        MISSING=1

        # iterate over existing forwarding rules to figure out which are missing
        for ruleIp in `iptables -L -t nat | grep DNAT | tr -s [:blank:] | cut -d' ' -f8 | cut -d':' -f 2` ; do

            if [ "$containerIp" == "$ruleIp" ]; then

                MISSING=0

                break
            fi

        done

        if [ "$MISSING" == 1 ]; then

            MISSING_IPS+=($containerIp)

        fi
    done

    # restore forwarding rules
    for ipaddr in "${MISSING_IPS[@]}" ; do

        port=$(expr 10000 + `echo $ipaddr | cut -d'.' -f4`)

        vlan=$(subutai list i | grep $ipaddr | cut -f1 | awk -F'-' '{print $(NF-1)}')

        iptables -t nat -A PREROUTING -i p2p$vlan -p tcp -m tcp --dport $port -j DNAT --to-destination $ipaddr:22

    done


    #remove forwarding rules for missing (destroyed) containers
    MISSING_RULES=()

# set line separator
IFS='
'
    # iterate over existing forwarding rules
    for rule in `iptables -L -t nat --line-numbers | grep DNAT | tr -s [:blank:]` ; do

        MISSING=1

        # iterate over IPs of running containers to figure out which rules are obsolete
        for containerIp in `subutai list i | grep -e 'RUNNING.*172.' | tr -s [:blank:] | cut -f3` ; do

            if [ -z "${rule##*$containerIp*}" ] ;then

                MISSING=0

                break
            fi

        done

        if [ "$MISSING" == 1 ]; then

            MISSING_RULES+=($rule)

        fi

    done

    # remove forwarding rules
    for rule in "${MISSING_RULES[@]}" ; do

        iptables -t nat -D PREROUTING $( echo $rule | awk '{print $1}')

    done

}


while true; do

    checkNRestore;

    sleep 30

done
